djangobasico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('favoritos.urls'))
]

favoritos/urls.py
from django.urls import path
from .views import *

app_name = 'favoritos'  

urlpatterns = [
    path('crear/', crear, name='crear'),
    path('', lista, name='lista'),
    path('borrar/<int:pk>', borrar , name='borrar'),
    path('editar/<int:pk>', editar, name='editar')
]

favoritos/models.py
from django.db import models

# Create your models here.

class Favorito(models.Model):
    nombre = models.CharField(max_length=50)
    url = models.URLField()

favoritos/forms.py
from django import forms
from .models import Favorito

class FavoritoModelForm(forms.ModelForm):
    class Meta:
        model = Favorito
        fields = '__all__'
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'url' : forms.URLInput(attrs={'class' : 'form-control'}),
        }

favoritos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Favorito
from .forms import FavoritoModelForm

def crear(request):

    titulo = 'Crear'

    form = FavoritoModelForm()
    if request.method == 'POST':
        form = FavoritoModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('favoritos:lista'))
        else:
            print(form.errors)   
    context = {
        'form' : form,
        'titulo' : titulo
        } 
    return render(request, 'crear.html', context)

def lista(request):

    objetos = Favorito.objects.all()
    contexto = {
        'favoritos' : objetos,
    }
    
    return render(request, 'lista.html', contexto)

def borrar(request, pk):
    Favorito.objects.get(pk=pk).delete()
    return redirect(reverse('favoritos:lista'))

def editar(request, pk):

    titulo = 'Editar'

    obj = Favorito.objects.get(pk=pk)

    if request.method == 'POST':
        form = FavoritoModelForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('favoritos:lista'))
    else:
        form = FavoritoModelForm(instance = obj)
    context = {
        'form' : form,
        'titulo' : titulo
    }
    return render(request,'crear.html', context)

templates/crear.html
{% extends 'index.html' %}

{% block title %} {{titulo}} {% endblock %}

{% block content %}

    <h1> {{titulo}} Favorito </h1>

    <form class="form" action="" method="post"> {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="{{titulo}}" class="btn btn-primary">
    </form>

    <br>

    <a href="{% url 'favoritos:lista' %}">Volver</a>

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoApp {% block title %} {% endblock %} </title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/lista.html
{% extends 'index.html' %}

{% block title %} Lista {% endblock %}

{% block content %}

    <h1>Lista de favoritos</h1>
    <hr>

    <table class="table table-bordered table-hover">
        <tr>
            <td><strong>Nombre</strong></td>
            <td><strong>Url</strong></td>
            <td><strong>Opciones</strong></td>
        </tr>

        {% for fav in favoritos %}

            <tr>
                <td> {{fav.nombre}} </td>
                <td> <a href="{{fav.url}}">{{fav.url}}</a> </td>
                <td><a href="{% url 'favoritos:borrar' fav.pk %}">Borrar</a> | <a href="{% url 'favoritos:editar' fav.pk %}">Editar</a></td>
            </tr>

        {% endfor %}

    </table>

    <a href="{% url 'favoritos:crear' %}">Crear Favorito</a>

{% endblock %}